[package]
name = "drupal-loadtest"
version = "0.1.0"
authors = ["Jeremy Andrews <jeremy@tag1consulting.com>"]
edition = "2018"

[dependencies]
#goose = "0.5"
goose = { path = "../goose" }
rand = "0.7"
scraper = "0.11.0"
